name: NPM Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Auto-increment current version by'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      confirm:
        description: 'Type `yes` to confirm to publish the package into the NPM registry and create a version commit and tag'
        required: true
        type: string

permissions:
  contents: write

# `FORCE_COLOR` is used by `chalk`, which is used internally by `mocha`.
# https://github.com/chalk/chalk#supportscolor
# https://github.com/orgs/community/discussions/26944#discussioncomment-3254075
env:
  FORCE_COLOR: 3

jobs:

  publish:
    if: inputs.confirm == 'yes'
    runs-on: ubuntu-latest
    permissions:
      # contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: echo "Version $VERSION | Confirm $CONFIRM"
        env:
          VERSION: ${{ inputs.version }}
          CONFIRM: ${{ inputs.confirm }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm run test
      
      - name: Set up git user name and email to be able to commit
        run: |
          git config user.name 'acuarica'
          git config user.email 'acuarica@users.noreply.github.com'

      - run: 'npm version ${{ inputs.version }} --message ":rocket: Bump new version v%s"'
      # https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry
      # - run: npm publish --provenance --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Push `package.json` bump commit and newly created tag for this release
        run: |
          git push
          git push --tags
